channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda
  - pyg
  - networkx=3.1
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - jupyterlab 
  - wandb
  - pip:
    - absl-py==1.2.0
    - deepchem==2.5.0
    - jax==0.2.17
    - opt-einsum==3.3.0
    - torchdrug==0.1.3
    - geomloss==0.2.5
    - tensorflow==2.9.1
