universe = docker
docker_image = gerritgr/deepset:latest
executable = run.sh
output = train_mgg.$(ClusterId).$(ProcId).out
error = train_mgg.$(ClusterId).$(ProcId).err
log = train_mgg.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 0
request_CPUs = 1
request_memory = 32G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue
